feat: log failure

diff --git a/includes.container/usr/share/vso/hooks/apt-post b/includes.container/usr/share/vso/hooks/apt-post
--- a/includes.container/usr/share/vso/hooks/apt-post
+++ b/includes.container/usr/share/vso/hooks/apt-post
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 package="$(cat /tmp/vso-transaction)"
+log_file="/tmp/vso-export-log.log"
 
 if [ -n "$SUDO_USER" ]; then
   username=$SUDO_USER
@@ -8,4 +9,9 @@ else
   echo "VSO does not work with root privileges, no programs will be exported. Use 'vso export -a $package' to manually export it."
 fi
 
-su -c "/usr/bin/vso export -a $package" $username
+su -c "/usr/bin/vso export -a $package" $username >> "$log_file" 2>&1
+
+if [ $? -ne 0 ]; then
+  echo "Error occurred while exporting. Check $log_file for details."
+  echo "No programs will be exported. Use 'vso export -a $package' to manually export it."
+fi
